### ISSUE TITLE
[CoreMotion] UI API called on a background thread on iOS 12 only and on iPhone X, iPhone XS and iPhone XS Max

### ISSUE THREAD

**Issue by Boggartfly** [ResearchKit/ResearchKit#1239]
**Steps to reproduce the problem:**
1. Configure the SDK and use on iPhone X, iPhone XS or iPhone XS Max
```
// WalkTask is a basic ORKOrderedTask
let taskViewController = ORKTaskViewController(task: WalkTask, taskRun: nil)
taskViewController.delegate = self
taskViewController.outputDirectory = NSURL(fileURLWithPath: NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0] , isDirectory: true) as URL
self.present(taskViewController, animated: true, completion: nil)
```

2. Launch the app

**Expected Behavior:**
No error in xcode debug window.

**Actual Behavior**
```
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 5766, TID: 1813921, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001d89ab534 <redacted> + 56
5   CoreMotion                          0x00000001df234040 CoreMotion + 307264
6   CoreMotion                          0x00000001df234574 CoreMotion + 308596
7   CoreMotion                          0x00000001df234484 CoreMotion + 308356
8   CoreMotion                          0x00000001df265c64 CoreMotion + 511076
9   CoreMotion                          0x00000001df265cc4 CoreMotion + 511172
10  CoreFoundation                      0x00000001d9744354 <redacted> + 28
11  CoreFoundation                      0x00000001d9743c38 <redacted> + 276
12  CoreFoundation                      0x00000001d973ef14 <redacted> + 2324
13  CoreFoundation                      0x00000001d973e2e8 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001d973f04c CFRunLoopRun + 84
15  CoreMotion                          0x00000001df2655fc CoreMotion + 509436
16  libsystem_pthread.dylib             0x00000001d93b8974 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001d93b88d0 _pthread_start + 52
18  libsystem_pthread.dylib             0x00000001d93c0ddc thread_start + 4
2019-02-12 14:39:24.873067-0500 GaitID[5766:1813921] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 5766, TID: 1813921, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001d89ab534 <redacted> + 56
5   CoreMotion                          0x00000001df234040 CoreMotion + 307264
6   CoreMotion                          0x00000001df234574 CoreMotion + 308596
7   CoreMotion                          0x00000001df234484 CoreMotion + 308356
8   CoreMotion                          0x00000001df265c64 CoreMotion + 511076
9   CoreMotion                          0x00000001df265cc4 CoreMotion + 511172
10  CoreFoundation                      0x00000001d9744354 <redacted> + 28
11  CoreFoundation                      0x00000001d9743c38 <redacted> + 276
12  CoreFoundation                      0x00000001d973ef14 <redacted> + 2324
13  CoreFoundation                      0x00000001d973e2e8 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001d973f04c CFRunLoopRun + 84
15  CoreMotion                          0x00000001df2655fc CoreMotion + 509436
16  libsystem_pthread.dylib             0x00000001d93b8974 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001d93b88d0 _pthread_start + 52
18  libsystem_pthread.dylib             0x00000001d93c0ddc thread_start + 4
```

**Comment by Boggartfly** [comment]
Anyone know if this can be fixed within the library? Or is this something that needs a bug report rdar at Apple?

**Comment by Boggartfly** [comment]
This is referenced at[ rdar://45003816](https://openradar.appspot.com/45003816)

**Comment by Boggartfly** [comment]
Hey @srinathtm-apple et al, Can you please help me out here? Is there a workaround for this until Apple fixes the bug?

**Comment by srinathtm-apple** [comment]
@Boggartfly - looks like this has been fixed in iOS 12.1.1, can you please update and verify?

**Comment by Boggartfly** [comment]
I'm on iOS 12.1.4 iPhone XS Max and this still does not work.

**Comment by Boggartfly** [comment]
I've filed a rdar on bugreport.apple.com and engineering has marked by bug as a duplicate. Lets hope they fix this soon.

**Comment by cwestMobile** [comment]
Any update?

**Comment by Boggartfly** [comment]
> Any update?

This issue still persists. Until Apple releases a patch here, unfortunately we are out of luck until then...

**Comment by Boggartfly** [comment]
> > Any update?
> 
> This issue still persists. Until Apple releases a patch here, unfortunately we are out of luck until then...

They mentioned it as a duplicate, when I got a reply from engineering.

**Comment by Boggartfly** [comment]
This is still not fixed within iOS 12.2. Just recently updated my iPhone XS Max, and lo and behold big anti-climax. Bug not yet fixed.
