### ISSUE TITLE
Passcode screen does not appear

### ISSUE THREAD

**Issue by majidsaleem105** [ResearchKit/ResearchKit#1427]
Hello everyone,

We have an app using the CareKit framework and it is working great but a few of our users are experiencing a very strange issue. After the successful authentication, we ask users to set up a passcode for quick access, the PassCode screen does not appear for some of the people and they can't use the app.

It displays the following message in the console Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default

We tried to use the different keyboard types but none of them is working.
![number-pad-keyboard](https://user-images.githubusercontent.com/1611600/97873638-bf043f00-1d39-11eb-8b60-75cbda183542.png)

It has been working since 2016 but suddenly, it starts causing issues after the iOS 12 release.
People are using the latest iPhone models iPhone X, 11, 11 Pro with iOS 13 & 14.
Please note that we're experiencing this issue on Real Devices, not in Simulators.

Please advise on this issue that how it can be fixed?

Thanks,
- Majid S.

**Comment by Pariecemckinney-apple** [comment]
Hello @majidsaleem105 , thank you for reaching out. Which version of ResearchKit are you currently using?

**Comment by majidsaleem105** [comment]
Hello @Pariecemckinney-apple, thanks for your prompt reply. We're facing this issue with the old RK version 1.5.

**Comment by Pariecemckinney-apple** [comment]
@majidsaleem105, do you have clear set of steps to reproduce the issue on your end? Or is it completely random? Any details at all would definitely help me dial in on the issue much faster. Also, you said after "iOS 12" release, so has this issue been going on for a while? 

I'll definitely keep investigating in the meantime! Thanks in advance.

**Comment by majidsaleem105** [comment]
Hello @Pariecemckinney-apple,

It's completely a random issue. As I said that it doesn't happen to everyone but a few of our users are facing this issue. Yes, we noticed this issue first time with iOS 12 but it was resolved with an alternate solution. At the start, we created `orderedTasks` with the following steps: 
LoginStep, WaitStep, PasscodeStep, DisclaimerStep, CompletionStep. So we split these steps into the following two `orderedTasks`.

1st Ordered Tasks: LoginStep, WaitStep, CompletionStep.
2nd Ordered Tasks: PasscodeStep, DisclaimerStep, CompletionStep.

This solution resolved the issue for iOS 12. Then we received a few complaints with iOS 13 but now with iOS 14, the number of complaints is increased. Almost daily, we are receiving complaints.

Thanks,
- Majid S.

**Comment by pthealthtech** [comment]
We tried removing the passcode step but the issue is still happening. We've had several more patient complaints today, most of them are using an iPhone 11 Pro.

**Comment by pthealthtech** [comment]
We just got our first iPhone 12 call.

**Comment by Pariecemckinney-apple** [comment]
@majidsaleem105 So the original solution was just to put the passcodeStep first within an ordered task and nothing else? I understand that its random but have you had the ability on your end to actually reproduce it at all? It's very hard to tie the issue to ResearchKit if it's completely random and can't be reproduced. We will keep trying different paths in order to resurface the issue but if you could give us specific steps that would help a bunch.

**Comment by Pariecemckinney-apple** [comment]
@pthealthtech what do you mean by removing the passcodeStep? So you removed it but the next step still won't show?

**Comment by majidsaleem105** [comment]
@Pariecemckinney-apple Yes, we put the passcodeStep at the first position and it worked for iOS 12 and iOS 13. A few users with iOS 13 faced this issue but the number was very minimal. We received many complaints after the iOS 14 release so we removed the passcodeStep screen temporarily so our patients can log into the app and use it.

Is this possible for you to get a previous version of our app from the store?

We're working on the new versions but we've some urgent requests and we have to deliver these tasks.

**Comment by pthealthtech** [comment]
Hi @Pariecemckinney-apple, is there any update on this issue?

**Comment by pthealthtech** [comment]
Hi @Pariecemckinney-apple, is there any update on this issue?

**Comment by Pariecemckinney-apple** [comment]
Hello @pthealthtech, I've been trying to reproduce to the issue but haven't had much luck. Again, this is pretty difficult to do without any screenshots or solid steps to re-surface the issue. I can try this within the catalog app but its still a strong chance that the setup might be very different within your app itself. 

I will keep trying on my side but if you could test things locally on your end and provide some kind of images or videos of the issue it would help immensely! Thanks, and I hope we can find a solution soon.

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we’ve published new versions of ResearchKit to main and haven’t seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
